language: ruby
env:
  global:
    - ORIENTATION_EMAIL_WHITELIST=hanso.dk
matrix:
  include:
    - rvm: 2.3.0
    - rvm: 2.2.4
      env: CUSTOM_RUBY_VERSION=2.2.4 ISOLATED=true
    - rvm: 2.1.8
      env: CUSTOM_RUBY_VERSION=2.1.8 ISOLATED=true

  fast_finish: true
  allow_failures:
    - 2.2.4
    - 2.1.8

sudo: false
bundler_args: --deployment --without development
cache:
  - bundler
  - directories:
    - bower_components
    - node_modules
before_script:
  - ruby --version
  - cp config/database.ci.yml config/database.yml
  - cp .env.example .env
  - psql -c 'create database orientation_test;' -U postgres
  - npm install -g bower
  - bower install
  - bundle exec rake db:migrate
script:
  - bundle exec rspec spec/
branches:
  only:
    - master
notifications:
  email: false
addons:
  postgresql: "9.3"
  code_climate:
    repo_token: 75408d377a0b3c1ab512bf3fb634617bccf2a1065f8c513e352139427ec8e1fb
